### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by christyanbrayan** [christyanbrayan/fresco#1]
- [ ] Ajustar responsividade;
- [ ] Atualizar rodapé com links;
- [ ] Adicionar Google Analytics;
- [ ] Minificar arquivos;
- [ ] Verificar porque fica quebrado localmente e no GH Pages;

**Comment by christyanbrayan** [comment]
https://youtu.be/AKzLuPlDlRQ?si=LtkzPMH6hMhrPiWO

**Comment by christyanbrayan** [comment]
https://www.youtube.com/watch?v=2HHDEP2kYY0&ab_channel=JamesMoro
